language: android

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "theta4j"

android:
  components:
    - build-tools-23.0.1
    - android-22
    - extra-android-support
    - extra-android-m2repository

script:
  - ./gradlew test
  - ./gradlew sonarqube

before_deploy: ./gradlew build

deploy:
  provider: releases
  api_key:
    secure: LXNth6sAtLEGuyjfGMv4PqeSob5wVdZDvI5FDdT7oolXq5vq/TxKizo0tYEMycSy3zYguXlHOW+ljXSGH40MMBlhvbzovKsefVPsh+MZYPBQfCH8tdsCsRf/lYWb1Eg8ZSq1OzWjSXEAac94uvFAVM92pUud5j6A7pga2982YUM=
  skip_cleanup: true
  file:
    - lib/build/libs/theta4j-$TRAVIS_TAG.jar
    - lib/build/libs/theta4j-$TRAVIS_TAG-javadoc.jar
  on:
    repo: shrhdk/theta4j
    tags: true
    all_branches: true
